Add support mesh default backend
allegro/vaas pull request #302
Opened 2021-05-24 10:39 UTC by awmackowiak

2021-05-26 09:35 UTC, ziollek requested changes

2021-05-26 09:35 UTC, ziollek commented on vaas-app/src/vaas/vcl/tests/expected-vcl-4.0-with-envoy.vcl
> +sub vcl_recv {
I guess that would be good idea to explicitly use default backend ;)

```
set req.backend_hint = default;
```

2021-05-26 11:48 UTC, awmackowiak commented on vaas-app/src/vaas/manager/migrations/0005_director_envoy_service.py
>              name='envoy_service_name',
yeah. I thought after that name could be more unprecise :)

2021-05-26 11:49 UTC, awmackowiak commented on vaas-app/src/vaas/vcl/renderer.py
> +        elif tag_name in ('ROUTER', 'EXPLICITE_ROUTER', 'DIRECTORS', 'RECV'):
Not require. Only mesh flag from cluster. I change it

2021-05-26 13:51 UTC, ziollek requested changes

2021-05-26 13:51 UTC, ziollek commented on vaas-app/src/vaas/vcl/renderer.py
> +        elif tag_name in ('ROUTER', 'EXPLICITE_ROUTER', 'DIRECTORS', 'RECV'):
👍

2021-05-26 13:51 UTC, ziollek commented on vaas-app/src/vaas/vcl/tests/expected-vcl-4.0-with-mesh_service.vcl
> +    set req.backend_hint = default;
I thought about putting that line in vcl_recv otherwise it will be duplicated in each use_director sub.

2021-05-27 08:46 UTC, ziollek approved these changes

2021-05-27 09:08 UTC, ziollek approved these changes

2021-05-27 12:15 UTC, ziollek approved these changes

2021-05-27 12:26 UTC, smigacz approved these changes

2021-05-27 13:04 UTC, sobczak-m approved these changes

2021-05-28 05:01 UTC, merged