Do not mix route action and director action
allegro/vaas pull request #325
Opened 2021-11-08 14:40 UTC by ziollek

2021-11-08 18:00 UTC, jtaczanowski requested changes

2021-11-08 18:00 UTC, jtaczanowski commented on vaas-app/src/vaas/vcl/tests/expected-vcl-4.0.vcl
> +    if(req.http.x-action != "nobackend" && ) {
Tutaj nie potrzebnie zozstało `&&`

2021-11-08 18:00 UTC, jtaczanowski commented on vaas-app/src/vaas/vcl/tests/expected-vcl-4.0-with-mesh_service.vcl
> +    if(req.http.x-action != "nobackend" && ) {
Tutaj nie potrzebnie zozstało `&&`
I tutaj: https://github.com/allegro/vaas/pull/325/files#diff-17834aa90862397bcdc08335b29c08fcdf2fd174db9ed362ce2b5605b46ea20fR432

2021-11-08 18:00 UTC, jtaczanowski commented on vaas-app/src/vaas/vcl/tests/expected-vcl-4.0-with-mesh-and-standard-service.vcl
> +    if(req.http.x-action != "nobackend" && ) {
Tutaj nie potrzebnie zozstało `&&`

2021-11-08 18:00 UTC, jtaczanowski commented on vaas-app/src/vaas/vcl/tests/expected-vcl-4.0-canary.vcl
> +    if(req.http.x-action != "nobackend" && ) {
Tutaj nie potrzebnie zozstało `&&`

2021-11-08 18:00 UTC, jtaczanowski commented on vaas-app/src/vaas/vcl/templates/vcl_blocks/4.0/SET_ACTION.tvcl
> +    if(req.http.x-action != "nobackend" && ) {
Tutaj nie potrzebnie zozstało `&&`

2021-11-09 06:02 UTC, ziollek commented on vaas-app/src/vaas/vcl/tests/expected-vcl-4.0.vcl
> +    if(req.http.x-action != "nobackend" && ) {
fixed

2021-11-09 06:06 UTC, TheMickeyMike approved these changes

2021-11-09 06:08 UTC, awmackowiak approved these changes

2021-11-09 07:20 UTC, sobczak-m approved these changes

2021-11-09 08:57 UTC, merged